### PR TITLE
fix: removing @JsonManagedReference

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Review by cmoulliard — COMMENTED** [review]
Do we have to extend an existing test case ?

**Comment by aureamunoz** [comment]
> Do we have to extend an existing test case ?

We should, let me see

**Comment by aureamunoz** [comment]
I don't know why this is not reproducible when no-native build so adding a tests doesn't make sense. The current tests should fail.
cc @cmoulliard @Sgitario

**Comment by Sgitario** [comment]
@aureamunoz can you rebase this pull request? After CI is green, we can merge it.

> I don't know why this is not reproducible when no-native build so adding a tests doesn't make sense. The current tests should fail. cc @cmoulliard @Sgitario

I guess this is because we can resolve the type when running in JVM mode, but not in Native, so it uses the default value `defaultReference` and makes the test to fail.

**Comment by Sgitario** [comment]
I tried these changes and now the native build is working fine.
@aureamunoz please rebase this pull request to ensure everything works fine with the latest changes (e2e coverage in CI) and we can merge it.

**Pull request merged**
