### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by aureamunoz**

### CODE REVIEW

**Comment by Sgitario** [comment]
To fix the failing test, you need to add the mock for kubernetes client in HomeResourceTest.

**Comment by aureamunoz** [comment]
> 

Why? This is not the case for the other tests, why would be needed for the `/services/discovered`one that I think is the only one failing?

**Comment by Sgitario** [comment]
> > 
> 
> Why? This is not the case for the other tests, why would be needed for the `/services/discovered` one that I think is the only one failing?

That's a good point. Going to the `/services/discovered` page should not have anything to do with the Kubernetes client.
I think the problem is that it's doing a real call to Kubernetes (because the Kubernetes client is not mocked). But it's true that this should not make the page to fail.

**Comment by cmoulliard** [comment]
Do you want to fix superHero Job part of this PR or to fix it in a new PR the CI/CD job where we will replace superHero with with Atomic fruits to use the same data, application, etc as we use for demo purposes and as documented ? WDYT: @aureamunoz @Sgitario

**Comment by aureamunoz** [comment]
> Do you want to fix superHero Job part of this PR or to fix it in a new PR the CI/CD job where we will replace superHero with with Atomic fruits to use the same data, application, etc as we use for demo purposes and as documented ? WDYT: @aureamunoz @Sgitario

I've just made a change to see if fixes it. Even if we modify the test for having atomic-fruits, I would like to have the super-heroes working as a guaranty of non regression a this point. But if you want to move forward we can do it in another PR.

**Comment by cmoulliard** [comment]
> Even if we modify the test for having atomic-fruits, I would like to have the super-heroes working as a guaranty of non regression a this point.

Ok to wait till you will fix it then

**Comment by cmoulliard** [comment]
LGTM and many thanks for your help @Sgitario @aureamunoz :-)

**Pull request merged**
